[group-1]
192.0.2.10 ansible_port=22

[group-2]
192.0.2.20

[all:vars]
ansible_user=demo
ansible_port=22
ansible_ssh_private_key_file=~/.ssh/id_ed25519
ansible_become=yes
ansible_become_method=sudo
ansible_become_password=''
# При необходимости проброс через bastion:
# ansible_ssh_common_args='-o ProxyCommand="ssh -i ~/.ssh/id_ed25519 -W %h:%p -p 22 user@bastion.example.com"'
